version: '3'

networks:
    app:

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - 80:80
        depends_on: 
            - mysql
            - golang
            - react_admin
            - react_client
        networks: 
            - app

    react_client: 
        restart: always
        build:
            context: .
            dockerfile: node.Dockerfile
            target: client
        ports:
            - 5000:5000  
        environment: 
            PORT: 5000
        networks: 
            - app

    react_admin: 
        restart: always
        build:
            context: .
            dockerfile: node.Dockerfile
            target: admin
        ports:
            - 5001:5001 
        environment: 
            PORT: 5001
        networks: 
            - app

    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "RGTESTST20211907"
            MYSQL_DATABASE: ruangguru_client
            MYSQL_USER: rg_test
            MYSQL_PASSWORD: "RGTESTST20211907"
        ports:
            - 3306:3306
        networks: 
            - app

    golang: 
        build: 
            context: .
            dockerfile: go.Dockerfile
        ports: 
            - 8080:8080
        restart: unless-stopped
        networks: 
            - app