version: '3.7'

networks:
    app:

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - 80:80
        depends_on: 
            # - mysql
            - golang
            - react_admin
            - react_client
        networks: 
            - app

    react_client: 
        restart: always
        build:
            context: .
            dockerfile: node.Dockerfile
            target: client
        ports:
            - 5000:5000  
        environment: 
            PORT: 5000
            REACT_APP_PUBLIC_API_URL: https://us-central1-silicon-airlock-153323.cloudfunctions.net
            REACT_APP_ADMIN_URL: http://143.198.183.254:5001
            REACT_APP_API_URL: http://143.198.183.254:8080
        networks: 
            - app

    react_admin: 
        restart: always
        build:
            context: .
            dockerfile: node.Dockerfile
            target: admin
        ports:
            - 5001:5001 
        environment: 
            PORT: 5001
            REACT_APP_PUBLIC_API_URL: https://us-central1-silicon-airlock-153323.cloudfunctions.net
            REACT_APP_API_URL: http://143.198.183.254:8080
        networks: 
            - app

    # mysql:
    #     image: mysql:5.7
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: RGTESTST20211907
    #         MYSQL_DATABASE: ruangguru_client
    #         MYSQL_USER: rg_test
    #         MYSQL_PASSWORD: RGTESTST20211907
    #     ports:
    #         - 3306:3306
    #     networks: 
    #         - app

    golang: 
        build: 
            context: .
            dockerfile: go.Dockerfile
        ports: 
            - 8080:8080
        restart: unless-stopped
        env_file:
            - .env
        environment:
            APP_PORT: 8080
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: rg_test
            DB_PASSWORD: RGTESTST20211907
            DB_DATABASE: ruangguru_client
            JWT_SECRET: IblvPMNKeRQ9bw9g5r0nRQ6J3i7oydqmmxL2UrbsJYZlrQPA5i1xhi9FAu3GHfFp
        networks: 
            - app